services:
    mongodb:
        image: mongo
        container_name: mongodb
        volumes:
            - mongodb_data:/data/db

    backend:
        build:
            context: ${BACKEND_PATH}
            target: production
        container_name: backend
        restart: always
        environment:
            AUTH_SECRET: ${AUTH_SECRET}
            AUTH_GITHUB_ID: ${AUTH_GITHUB_ID}
            AUTH_GITHUB_SECRET: ${AUTH_GITHUB_SECRET}
            MONGODB_URI: ${MONGODB_URI}
            MAGIC_USER_LOGIN: ${MAGIC_USER_LOGIN}
            MAGIC_USER_PASSWORD: ${MAGIC_USER_PASSWORD}
        ports:
            - "${PORT}:80"
        volumes:
            - backend_data:/app
            - frontend_dist:/app/public
        depends_on:
            - mongodb

    frontend:
        build:
            context: ${FRONTEND_PATH}
            target: build
        environment:
            VITE_OUTDIR: dist
        container_name: frontend_builder
        volumes:
            - frontend_dist:/app/public
        command: /bin/sh -c "npm run build && cp -R dist/* /app/public/" # Copie le contenu de dist dans /app/public après le build
        depends_on:
            - backend

volumes:
    mongodb_data:
    backend_data:
    frontend_dist:
